name: Go

on:
  push:
    branches: [ main ]
    tags:
    - '*'

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./ && ls
      
    - uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: ./discord-bot
      
  build-windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./ && dir
      
    - uses: actions/upload-artifact@v2
      with:
        name: windows-binary
        path: ./discord-bot.exe
      
  release:
    runs-on: ubuntu-latest
    needs: [build-linux , build-windows]
    steps:
    - name: Download artifact
      uses: aochmann/actions-download-artifact@1.0.4
      with:
        github_token: ${{github.token}}
        repo: ${{github.repository}}
        path: ./
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: discord-bot, discord-bot.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
